name: start deploy to test

on:
  push:
    branches:
      - release

jobs:
    
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, GitHub Actions!"

  checkoutToMain:
    runs-on: ubuntu-latest
    needs:  build
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Merge feature branch into develop
          run : git push origin release:main

  pushToRelease:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push code to release
        run : git push origin develop:release

