name: start deploy to test

on:
  push:
    branches:
      - release

jobs:
    
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, GitHub Actions!"

  checkoutToMain:
    runs-on: ubuntu-latest
    needs:  build
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Merge release branch and main
          env:
            GITHUB_TOKEN: ${{ secrets.pat }}
          run : |
            git config --global user.email "patelharsha2000@gmail.com"
            git config --global user.name "HARSHA2000" 
            git checkout main
            git merge --no-ff release 
            git push origin main

#   pushToRelease:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/develop'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Push code to release
#         env:
#             GITHUB_TOKEN: ${{ secrets.pat }}
#         run :
#             git config --global user.email "patelharsha2000@gmail.com"
#             git config --global user.name "HARSHA2000" 
#             git push origin develop:release

